#!/usr/bin/env python
"""
🤖 Earner Agent — GitHub Actions Mode
24/7 autonomous earning without any user input.
Runs on schedule, thinks, searches, creates value.
"""

import sys, os, json, time
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from llm import LLM
from tools import ToolRegistry, web_search, file_write
import memory as mem

# ─── Setup ───
mem.reset()
reg = ToolRegistry()

# ─── Helper ───
def log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}")

# ─── Think Phase ───
def think_earning_opportunity() -> str:
    """Use LLM to decide what earning opportunity to pursue"""
    l = LLM()
    if not l.api_key:
        log("❌ No GROQ_API_KEY set!")
        return ""

    prompt = """You are an autonomous earning agent running 24/7.
Your mission: FIND or CREATE income opportunities.

Think step by step:
1. FIRST: Do a web search for trending freelance projects / gigs
2. PICK one opportunity you can execute right now (coding, content, tool, script)
3. SAY what you'll build and why it can earn money

Use TOOL:web_search|PROMPT:... to search.
Then describe what you'll create.

Examples of earning opportunities:
- Python automation scripts ($50-500)
- Web scraping tools ($100-1000)
- LLM chatbots / integrations ($200-2000)
- Digital products (templates, icons, themes)
- Data analysis reports
- Content / blog posts about trending tech

Think like an entrepreneur. What can you build TODAY that has value?"""

    resp = l.chat([
        {"role": "system", "content": "You are an autonomous earning agent. Always use web_search first to check real trends."},
        {"role": "user", "content": prompt}
    ], max_tokens=2000)

    if resp and resp.get("content"):
        return resp["content"]
    return ""


# ─── Build Phase ───
def execute_earning_plan(plan: str):
    """Try to execute tools mentioned in the plan"""
    # Check for tool calls and execute them
    calls = []
    for line in plan.split("\n"):
        line = line.strip()
        if "TOOL:" in line and "|PROMPT:" in line:
            try:
                parts = line.split("TOOL:")[1].split("|PROMPT:")
                tool = parts[0].strip().lower()
                prompt = parts[1].strip()
                calls.append((tool, prompt))
            except:
                pass

    results = []
    for tool_name, prompt in calls[:5]:
        log(f"🔧 Executing {tool_name}...")
        try:
            result = reg.execute(f"{tool_name}|{prompt}")
            if result:
                results.append(f"\n### Tool: {tool_name}\n```\n{result[:500]}\n```")
                log(f"✅ {tool_name} done")
        except Exception as e:
            log(f"⚠ {tool_name} error: {str(e)[:100]}")
        time.sleep(1)

    return results


# ─── Save Report ───
def save_report(thinking: str, results: list, output: str):
    """Save the earnings report to file"""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    report_dir = Path("reports")
    report_dir.mkdir(exist_ok=True)

    report = f"""# 🤖 Earner Agent — Earning Report

**Date:** {date_str}  
**Time:** {time_str}  
**Status:** ✅ Complete

---

## 🧠 Agent Thinking

{thinking[:1000]}

---

## 🔧 Actions Taken

{chr(10).join(results) if results else "No tool actions were executed."}

---

## 💰 Earning Opportunity

{output[:500] if output else "—"}

---

## 📈 Summary

This report was automatically generated by the Earner Agent.
Next run: {date_str} (every 2 hours)
"""
    report_path = report_dir / f"earnings-{date_str}.md"
    report_path.write_text(report)
    log(f"📄 Report saved: {report_path}")

    # Save latest
    (report_dir / "latest.md").write_text(report)
    log(f"📄 Latest report updated")


# ─── Main ───
def main():
    log("=" * 50)
    log("🤖 EARNER AGENT — GitHub Actions Mode")
    log("=" * 50)
    log(f"Time: {datetime.now().isoformat()}")

    # 1. Think
    log("💭 Thinking about earning opportunities...")
    thinking = think_earning_opportunity()

    if not thinking:
        log("⚠ No thinking output — API issue?")
        save_report("⚠ No output from LLM", [], "")
        return

    log(f"✅ Agent response received ({len(thinking)} chars)")
    print(f"\n{'─'*50}")
    print(thinking[:800])
    print(f"{'─'*50}\n")

    # 2. Execute
    log("🔧 Executing earning plan...")
    results = execute_earning_plan(thinking)

    # 3. Also do a direct web search for trending freelance projects
    log("🔍 Searching for real freelancing opportunities...")
    try:
        search_result = reg.execute("web_search|freelancing python projects 2025 high paying remote")
        if search_result:
            log(f"🌐 Search done: {search_result[:200]}")
    except Exception as e:
        log(f"⚠ Search error: {e}")

    # 4. Save
    save_report(thinking, results, thinking)
    log("""
✅ Done! Earnings report saved.
Next run in 2 hours.
""")


if __name__ == "__main__":
    main()
